services:
  app:
    build:
      context: /Users/lucguo/study/laravel9
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "9000:9000"
    volumes:
      - /Users/lucguo/study/laravel9:/var/www
    environment:
      - PHP_FPM_INSTALL_PDO=true

  web:
    image: nginx:latest
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - /Users/lucguo/study/laravel9:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: laravel-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
